project:
  type: website

website:
  title: "Aidan Neeson - CMPSC 610"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: rf.qmd
        text: Random Forest
      - href: svm.qmd
        text: SVM
      - href: ann.qmd
        text: ANN

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



