name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code withiin the repository
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        # Perform markdown linting using mdl
        - name: Run Markdown Linting
          uses: actionshub/markdownlint@main
        # Setup Python as required for this tool
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.5'
        # Install pip
        - name: Install Pip
          run: |
            pip install -U pip
        # Install poetry
        - name: Install Poetry
          uses: abatilo/actions-poetry@v2.0.0
          with:
            poetry-version: 1.4.0
        # Install dependencies
        - name: Install dependencies
          run: |
            poetry install
        # Run the ruff linting rool
        - name: Run Ruff Linter
          run: |
            poetry run ruff check src
        # Run all python notebooks in the src directory
        - name: Run Notebooks
          run: |
            python -m pip install nbconvert nbformat
            jupyter nbconvert --to notebook --execute src/*.ipynb --ExecutePreprocessor.kernel_name='python3' --inplace